version: '3'
services:
  ngnix:
    image: nginx:alpine
    volumes:
      - "./Docker/nginx/default.conf:/etc/nginx/conf.d/default.conf"
      - "./:/var/www/html"
      - "./Docker/nginx/default.template.conf:/etc/nginx/conf.d/default.template"
    ports:
      - "8000:80"
      - "3000:443"
    environment:
      - NGINX_HOST=${NGINX_HOST}
    command: /bin/sh -c "envsubst '$$NGINX_HOST' < /etc/nginx/conf.d/default.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    restart: always
    depends_on:
      - php
      - redis
    networks:
      - default
  php:
    build:
      context: ./Docker/php/
    restart: always
    volumes:
#      - "./Docker/php/php.ini:/usr/local/etc/php/conf.d/php.ini"
      - "./:/var/www/html"
  redis:
    image: redis
    container_name: redis_container
    security_opt:
      - seccomp:unconfined
    networks:
      - default
    ports:
      - "6379:6379"

networks:
  default:
    ipam:
      config:
        - subnet: 172.20.0.0/24
